artifact_uri: file:C:\Documentos Melany\Especializacion en Analitica\Producto de datos\PRE-08-mlflow-tracking-local-MC-Melany\my_mlruns/921983778321137276/789e45dfca674aae9362759763a90baf/artifacts
end_time: 1748107617923
entry_point_name: ''
experiment_id: '921983778321137276'
lifecycle_stage: active
run_id: 789e45dfca674aae9362759763a90baf
run_name: knn_de3db15e
run_uuid: 789e45dfca674aae9362759763a90baf
source_name: ''
source_type: 4
source_version: ''
start_time: 1748107617759
status: 3
tags: []
user_id: melan
