artifact_uri: file:C:\Documentos Melany\Especializacion en Analitica\Producto de datos\PRE-08-mlflow-tracking-local-MC-Melany\my_mlruns/921983778321137276/717bb72a3ffe40b88abf8f5bf797005c/artifacts
end_time: 1748107606390
entry_point_name: ''
experiment_id: '921983778321137276'
lifecycle_stage: active
run_id: 717bb72a3ffe40b88abf8f5bf797005c
run_name: elasticnet_1a34d814
run_uuid: 717bb72a3ffe40b88abf8f5bf797005c
source_name: ''
source_type: 4
source_version: ''
start_time: 1748107606143
status: 3
tags: []
user_id: melan
